export default [
  { name: 'value / v-model', desc: '绑定值，控制对话框显示隐藏', type: 'Boolean', values: '-', default: 'false' },
  { name: 'header', desc: '显示头部，如果不显示，那么图标、标题、工具栏都不会显示', type: 'Boolean', values: '-', default: 'true' },
  { name: 'title', desc: '标题', type: 'String', values: '-', default: '-' },
  { name: 'icon', desc: '标题左侧图标', type: 'String', values: '-', default: '-' },
  { name: 'icon-color', desc: '标题左侧图标的颜色', type: 'String', values: '-', default: '-' },
  { name: 'width', desc: '宽度，仅支持px或者百分比%的格式', type: 'String', values: '-', default: '50%' },
  { name: 'height', desc: '高度，仅支持px或者百分比%的格式', type: 'String', values: '-', default: '自适应' },
  { name: 'top', desc: '距离顶部的高度，仅支持px或者百分比%的格式', type: 'String', values: '-', default: '50px' },
  { name: 'size', desc: '尺寸', type: 'String', values: 'medium / small / mini', default: '-' },
  { name: 'custom-class', desc: '自定义样式class', type: 'String', values: '-', default: '-' },
  { name: 'modal', desc: '是否显示模态框', type: 'Boolean', values: '-', default: 'true' },
  { name: 'close-on-click-modal', desc: '是否可以通过点击 modal 关闭 Dialog', type: 'Boolean', values: '-', default: 'true' },
  { name: 'show-close', desc: '是否显示顶部关闭按钮', type: 'Boolean', values: '-', default: 'true' },
  { name: 'show-fullscreen', desc: '是否显示顶部全屏按钮', type: 'Boolean', values: '-', default: 'true' },
  { name: 'before-close', desc: '关闭前执行的函数', type: 'Function', values: '-', default: '-' },
  { name: 'destroy-on-close', desc: '关闭时销毁 Dialog 元素', type: 'Boolean', values: '-', default: 'false' },
  { name: 'lock-scroll', desc: '是否在 Dialog 出现时将 body 滚动锁定', type: 'Boolean', values: '-', default: 'true' },
  { name: 'append-to-body', desc: 'Dialog 自身是否插入至 body 元素上。嵌套的 Dialog 必须指定该属性并赋值为 true', type: 'Boolean', values: '-', default: 'false' },
  { name: 'no-padding', desc: '不包含内边距', type: 'Boolean', values: '-', default: 'false' },
  { name: 'draggable', desc: '启用拖拽功能', type: 'Boolean', values: '-', default: 'false' },
  { name: 'drag-out-page', desc: '是否可拖出页面', type: 'Boolean', values: '-', default: 'false' },
  { name: 'drag-min-width', desc: '拖拽出页面后保留的最小宽度，单位px', type: 'Number', values: '-', default: '100' },
]
