export default [
  { name: 'value / v-model', desc: '绑定值，控制对话框显示隐藏', type: 'Boolean', values: '-', default: 'false' },
  { name: 'header', desc: '显示头部，如果不显示，那么图标、标题、工具栏都不会显示', type: 'Boolean', values: '-', default: 'true' },
  { name: 'title', desc: '标题', type: 'String', values: '-', default: '-' },
  { name: 'icon', desc: '标题左侧图标', type: 'String', values: '-', default: '-' },
  { name: 'icon-color', desc: '标题左侧图标的颜色', type: 'String', values: '-', default: '-' },
  { name: 'width', desc: '宽度，仅支持px或者百分比%的格式', type: 'String', values: '-', default: '50%' },
  { name: 'height', desc: '高度，仅支持px或者百分比%的格式', type: 'String', values: '-', default: '自适应' },
  { name: 'direction', desc: '方向', type: 'String', values: 'right / left / top / bottom', default: 'right' },
  { name: 'size', desc: '尺寸', type: 'String', values: 'medium / small / mini', default: '-' },
  { name: 'custom-class', desc: '自定义样式class', type: 'String', values: '-', default: '-' },
  { name: 'modal', desc: '是否显示模态框', type: 'Boolean', values: '-', default: 'true' },
  { name: 'close-on-click-modal', desc: '是否可以通过点击 modal 关闭 Drawer', type: 'Boolean', values: '-', default: 'true' },
  { name: 'show-close', desc: '是否显示顶部关闭按钮', type: 'Boolean', values: '-', default: 'true' },
  { name: 'show-fullscreen', desc: '是否显示顶部全屏按钮', type: 'Boolean', values: '-', default: 'true' },
  { name: 'before-close', desc: '关闭前执行的函数', type: 'Function', values: '-', default: '-' },
  { name: 'destroy-on-close', desc: '关闭时销毁 Drawer 元素', type: 'Boolean', values: '-', default: 'false' },
  { name: 'lock-scroll', desc: '是否在 Drawer 出现时将 body 滚动锁定', type: 'Boolean', values: '-', default: 'true' },
  { name: 'append-to-body', desc: 'Drawer 自身是否插入至 body 元素上。嵌套的 Drawer 必须指定该属性并赋值为 true', type: 'Boolean', values: '-', default: 'false' },
  { name: 'no-padding', desc: '不包含内边距', type: 'Boolean', values: '-', default: 'false' },
  { name: 'loading', desc: '显示加载动画', type: 'Boolean', values: '-', default: 'false' },
  { name: 'loading-text', desc: '加载动画文本', type: 'String', values: '-', default: '-' },
  { name: 'loading-background', desc: '加载动画模态框的背景色', type: 'String', values: '-', default: '-' },
  { name: 'loading-spinner', desc: '加载动画图标', type: 'String', values: '-', default: '-' },
]
